version: 2
jobs:
  build:
    machine: true
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: Install RubyGems
          command: |
            gem install bundler
            bundle install
            librarian-puppet init && librarian-puppet install
      - run:
          name: Validate & Rake it!
          command: |
            puppet parser validate .
            bundle exec rake
      - run:
          name: Kitchenifying
          command: |
            bundle exec kitchen test --concurrency 4 --parallel
